Try again with ECDSA deploy key
The previous build failed due to GitHub security considerations:

    Cloning into '../../usr/local/lib/node_modules/gh-pages/.cache/git@github.com!jfrimmel!gba-experiments.git'...
    ERROR: You're using an RSA key with SHA-1, which is no longer allowed. Please use a newer client or a different key type.
    Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.

    fatal: Could not read from remote repository.

This commit changes the fingerprint to a new ECDSA-key, which is already
set up on CircleCI and GitHub.